const logEntries = [
    {
        'id': 1,
        'createdAt': '2018-08-22 13:14:40',
        'subsystem': 'Run Coordination',
        'class': 'PROCESS',
        'type': 'GENERAL',
        'run': 284684,
        'author': 'Marco',
        'title': 'EOR report b839',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 2,
        'createdAt': '2018-01-26 13:11:40',
        'subsystem': 'Central DCS',
        'class': 'HUMAN',
        'type': 'GENERAL',
        'run': 284684,
        'author': 'Christopher',
        'title': 'EOR report b699',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 3,
        'createdAt': '2018-03-07 12:14:40',
        'subsystem': 'Run Coordination',
        'class': 'PROCESS',
        'type': 'GENERAL',
        'run': 284684,
        'author': 'Marco',
        'title': 'EOR report b485',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 4,
        'createdAt': '2018-06-25 10:14:40',
        'subsystem': 'Run Coordination',
        'class': 'PROCESS',
        'type': 'EOS',
        'run': 284684,
        'author': 'Maria',
        'title': 'EOR report b354',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 5,
        'createdAt': '2018-01-29 15:11:40',
        'subsystem': 'Multiple',
        'class': 'HUMAN',
        'type': 'EOS',
        'run': 284684,
        'author': 'Marco',
        'title': 'EOR report b889',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 6,
        'createdAt': '2018-01-22 16:11:50',
        'subsystem': 'PHOS',
        'class': 'PROCESS',
        'type': 'GENERAL',
        'run': 284684,
        'author': 'Sergey',
        'title': 'EOR report b42',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 7,
        'createdAt': '2018-08-20 17:19:40',
        'subsystem': 'Run Coordination',
        'class': 'PROCESS',
        'type': 'GENERAL',
        'run': 284684,
        'author': 'Marco',
        'title': 'EOR report b172',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 8,
        'createdAt': '2018-06-22 18:50:30',
        'subsystem': 'SPD',
        'class': 'PROCESS',
        'type': 'GENERAL',
        'run': 284684,
        'author': 'Marco',
        'title': 'EOR report b879',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 9,
        'createdAt': '2018-08-22 18:02:17',
        'subsystem': 'Run Coordination',
        'class': 'PROCESS',
        'type': 'GENERAL',
        'run': 284684,
        'author': 'Marco',
        'title': 'EOR report b37',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 10,
        'createdAt': '2018-08-22 20:07:30',
        'subsystem': 'Offline',
        'class': 'PROCESS',
        'type': 'HARDWARE',
        'run': 284684,
        'author': 'Marco',
        'title': 'EOR report b84',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 11,
        'createdAt': '2018-08-22 14:12:10',
        'subsystem': 'Run Coordination',
        'class': 'HUMAN',
        'type': 'GENERAL',
        'run': 284684,
        'author': 'Camille',
        'title': 'EOR report b142',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    },
    {
        'id': 12,
        'createdAt': '2018-11-17 08:06:30',
        'subsystem': 'DQM/QA',
        'class': 'HUMAN',
        'type': 'GENERAL',
        'run': 284684,
        'author': 'Lydia',
        'title': 'EOR report b123',
        'text': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid assumenda est illo itaque molestiae mollitia obcaecati perspiciatis rerum velit vitae.',
        'followUps': '',
        'files': []
    }
];

export default logEntries;
